# Generated by Django 3.1.1 on 2020-09-03 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Ubicacion', models.CharField(max_length=50)),
                ('Capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=15)),
                ('ApellidoMaterno', models.CharField(max_length=15)),
                ('Nombres', models.CharField(max_length=15)),
                ('DNI', models.CharField(max_length=8)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N', 'No especifica')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Tipo', models.CharField(max_length=50)),
                ('Estado', models.BooleanField(default=True)),
                ('Activ', models.ManyToManyField(to='Configuracion.Actividades')),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=15)),
                ('Cantidad', models.IntegerField()),
                ('Costo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('Asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configuracion.asistente')),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configuracion.evento')),
            ],
        ),
        migrations.AddField(
            model_name='actividades',
            name='Ambientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configuracion.ambientes'),
        ),
    ]
